name: lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Go environment
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: "stable"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0

      - uses: katexochen/go-tidy-check@427c8c07d3d83ab8d7290cad04ce71c12eab3674 # v2.0.1

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          severity: info

      - name: Run Actionlint
        shell: bash
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
          actionlint

      - name: Run govulncheck
        shell: bash
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          GOMEMLIMIT=5GiB govulncheck ./...
